name: Build

on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - master

jobs:
  release-build:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash

    steps:
    - name: Pull code from git
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '[15,16)'
        
#    - name: Setup .NET
#      uses: actions/setup-dotnet@v2
#      with:
#        dotnet-version: 5.0.x

    - name: Restore nuget packages
      run:  |
        cd "$GITHUB_WORKSPACE"
        ./build.sh --automation-mode --msbuild-path-2017 MSBuild.exe --restore

    - name: Build
      run:  |
        cd "$GITHUB_WORKSPACE"
        ./build.sh --automation-mode --msbuild-path-2017 MSBuild.exe --build

#    - name: Run unit tests for .NET Framework v4.6.2
#      run:  |
#        cd "$GITHUB_WORKSPACE"
#        ./build.sh --automation-mode --test-framework
#
#    - name: Run unit tests for .NET Core App v3.1
#      run:  |
#        cd "$GITHUB_WORKSPACE"
#        ./build.sh --automation-mode --test-core

    - name: Create artifact - MediaTesterLib
      uses: actions/upload-artifact@v3
      with:
        name: MediaTesterLib${{ env.BUILD_VERSION_SUFFIX }}
        path: _output/MediaTesterLib/*

    - name: Create artifact - MediaTesterCli
      uses: actions/upload-artifact@v3
      with:
        name: MediaTesterCli${{ env.BUILD_VERSION_SUFFIX }}
        path: _output/MediaTesterCli/*

    - name: Create artifact - MediaTesterGui
      uses: actions/upload-artifact@v3
      with:
        name: MediaTesterGui${{ env.BUILD_VERSION_SUFFIX }}
        path: _output/MediaTesterGui/*
